---
- repo: local
  hooks: 
  - id: yamllint
    name: yamllint
    entry: ./node_modules/.bin/yamllint -c ./yamllint/config/conf.yml .
    language: python
    types: [file, yaml, yml]
  
  - id: codeql
    name: codeql
    entry: ./node_modules/.bin/yamllint -c ./yamllint/config/conf.yml .
    language: python
    types: [file, yaml, yml]