apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ng-devops
  name: ng-devops
  namespace: ng-devops-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ng-devops
  template:
    metadata:
      labels:
        app: ng-devops
    spec:
      containers:
      - name: ng-devops
        image: chrisnt5/ng-devops:1.1.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            #memory: "1.5Gi"
            memory: "256Mi"
            #cpu: "1" - 500m is half a cpu
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
      restartPolicy: Always
