apiVersion: v1
kind: Service
metadata:
  labels:
    app: ng-devops
  name: ng-devops
  namespace: ng-devops-ns
spec:
  ports:
  - nodePort: 30005
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ng-devops
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ng-devops
  name: ng-devops
  namespace: ng-devops-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ng-devops
  template:
    metadata:
      labels:
        app: ng-devops
    spec:
      containers:
      - image: chrisnt5/ng-devops:1.1.3
        imagePullPolicy: IfNotPresent
        name: ng-devops
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
      restartPolicy: Always
